#!/usr/bin/env node
/**
 * Group the per-module CSS emitted by the lib build (`*.wyw-in-js.css`,
 * one file per module thanks to preserveModules + cssCodeSplit) into
 * consumer-facing subpaths:
 *
 *   dist/css/tokens.css        theme + design tokens (import once)
 *   dist/css/<component>.css   one file per component dir (kebab-case)
 *   dist/css/form.css          react-f0rm integration (FormItem)
 *   dist/haze-ui.css           full aggregate, served as 'haze-ui/styles.css'
 *
 * Components never import each other, so a component dir's CSS is
 * self-contained; tokens are the only shared layer and live in tokens.css.
 * Per-component files therefore require tokens.css (once), not each other.
 *
 * Invariants enforced at the end (non-zero exit on failure):
 *   - every `.wyw-in-js.css` file is covered by exactly one group
 *   - the aggregate's class-name set equals the union of module CSS
 *   - no dangling `.wyw-in-js.css` import/require survives in dist JS —
 *     the styles are carried by `haze-ui/styles.css` / `haze-ui/css/*`,
 *     so the per-module side-effect imports are stripped together with
 *     the files (1.11.0 shipped them dangling: Node ESM, vitest inline
 *     and vite build all fail to resolve the removed files)
 */
import { mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const distDir = path.join(path.dirname(fileURLToPath(import.meta.url)), '..', 'dist');
const cssDir = path.join(distDir, 'css');

const kebab = (name) =>
  name.replace(/([a-z0-9])([A-Z])/g, '$1-$2').replace(/([A-Z]+)([A-Z][a-z])/g, '$1-$2').toLowerCase();

/** Recursively collect `*.wyw-in-js.css` files as paths relative to dist/. */
function collectModuleCss(dir = distDir, prefix = '') {
  const files = [];
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const rel = prefix ? `${prefix}/${entry.name}` : entry.name;
    if (entry.isDirectory()) {
      files.push(...collectModuleCss(path.join(dir, entry.name), rel));
    } else if (entry.name.endsWith('.wyw-in-js.css')) {
      files.push(rel);
    }
  }
  return files;
}

const moduleCssFiles = collectModuleCss().sort();
if (moduleCssFiles.length === 0) {
  console.error('split-css: no *.wyw-in-js.css found under dist/ — did the lib build run?');
  process.exit(1);
}

// Map output name -> list of module css paths (relative to dist/).
const groups = new Map();
for (const rel of moduleCssFiles) {
  const segments = rel.split('/');
  let name;
  if (segments[0] === 'tokens') {
    name = 'tokens';
  } else if (segments[0] === 'components') {
    name = kebab(segments[1]);
  } else if (segments[0] === 'form') {
    name = 'form';
  } else {
    console.error(`split-css: unexpected module CSS location ${rel}`);
    process.exit(1);
  }
  if (!groups.has(name)) groups.set(name, []);
  groups.get(name).push(rel);
}

const read = (rel) => readFileSync(path.join(distDir, rel), 'utf8').trim();
const banner = (name) => `/* haze-ui ${name} — generated by scripts/split-css.mjs, do not edit */`;

mkdirSync(cssDir, { recursive: true });

// tokens first, then everything else alphabetically — deterministic output.
const orderedNames = [...groups.keys()].sort((a, b) =>
  a === 'tokens' ? -1 : b === 'tokens' ? 1 : a.localeCompare(b)
);

for (const name of orderedNames) {
  const body = groups.get(name).map(read).join('\n');
  writeFileSync(path.join(cssDir, `${name}.css`), `${banner(name)}\n${body}\n`);
}

// Full aggregate for the `haze-ui/styles.css` subpath.
const aggregate = orderedNames.map((name) => groups.get(name).map(read).join('\n')).join('\n');
writeFileSync(path.join(distDir, 'haze-ui.css'), `${aggregate}\n`);

// Class-set parity check: aggregate must contain exactly the union of all
// module classes (no lost and no duplicated-with-different-content rules).
const classSet = (css) => new Set(css.match(/\.haze-[A-Za-z0-9_-]+/g) ?? []);
const union = new Set();
for (const rel of moduleCssFiles) {
  for (const cls of classSet(read(rel))) union.add(cls);
}
const aggregateClasses = classSet(aggregate);
const missing = [...union].filter((c) => !aggregateClasses.has(c));
const extra = [...aggregateClasses].filter((c) => !union.has(c));
if (missing.length > 0 || extra.length > 0) {
  console.error(`split-css: aggregate mismatch (missing: ${missing}, extra: ${extra})`);
  process.exit(1);
}

// The per-module files are superseded by dist/css/* and dist/haze-ui.css;
// drop them so the published package ships each rule exactly once — and
// strip their side-effect imports from the JS outputs, otherwise the
// published package references files that no longer exist.
for (const rel of moduleCssFiles) {
  rmSync(path.join(distDir, rel));
}
stripDanglingCssImports();

/** Remove `import "./x.wyw-in-js.css"` / `require("./x.wyw-in-js.css")` from dist JS. */
function stripDanglingCssImports() {
  const jsExtensions = new Set(['.js', '.cjs', '.mjs']);
  const esmImport = /import\s*["'][^"']*\.wyw-in-js\.css["'];?/g;
  const cjsRequire = /require\(\s*["'][^"']*\.wyw-in-js\.css["']\s*\);?/g;
  const strip = (dir = distDir) => {
    let stripped = 0;
    for (const entry of readdirSync(dir, {withFileTypes: true})) {
      const full = path.join(dir, entry.name);
      if (entry.isDirectory()) {
        stripped += strip(full);
      } else if (jsExtensions.has(path.extname(entry.name))) {
        const code = readFileSync(full, 'utf8');
        const next = code.replace(esmImport, '').replace(cjsRequire, '');
        if (next !== code) {
          writeFileSync(full, next);
          stripped += 1;
        }
      }
    }
    return stripped;
  };
  const strippedFiles = strip();
  if (strippedFiles === 0) {
    console.error('split-css: no .wyw-in-js.css imports found in dist JS — build output shape changed?');
    process.exit(1);
  }
  console.log(`split-css: stripped dangling css imports from ${strippedFiles} JS files`);
}

const perComponent = orderedNames.filter((n) => n !== 'tokens').length;
console.log(
  `split-css: ${perComponent} component files + tokens.css + haze-ui.css (${union.size} classes) written to dist/css`
);
